nodeExporter:
  tolerations:
    - operator: "Exists"

configmapReload:
  prometheus:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 512Mi

server:
  replicaCount: 1
  retention: "15d"
  persistentVolume:
    size: "50Gi"
  accessModes:
    - ReadWriteMany
    
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  
  statefulSet:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    hosts:
      - prometheus.k8s.our-cluster.ovh
    tls: 
      - hosts:
        - prometheus.k8s.our-cluster.ovh
        secretName: prometheus-tls
    

kube-state-metrics:
  metricLabelsAllowlist:
    - nodes=[*]
    - pods=[*]
    - namespaces=[*]
  metricAnnotationsAllowList:
    - namespaces=[*]

grafana:
  enabled: false

alertmanager:
  enabled: false

pushgateway:
  enabled: false

