persistence:
  enabled: true
  
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    - grafana.k8s.our-cluster.ovh
  tls: 
    - hosts:
      - grafana.k8s.our-cluster.ovh
      secretName: grafana-tls
  
plugins:
  - trino-datasource
