output "api_url" {
  description = "Base URL of the deployed API Gateway stage"
  value       = aws_api_gateway_stage.andy.invoke_url
}

output "rest_api_id" {
  value = aws_api_gateway_rest_api.andy.id
}

output "stage_name" {
  value = aws_api_gateway_stage.andy.stage_name
}

output "custom_domain_url" {
  description = "Custom domain URL (empty if custom_domain was not set)"
  value       = local.enable_custom_domain ? "https://${var.custom_domain}" : ""
}

output "custom_domain_target" {
  description = <<-EOT
    Regional domain name generated by API Gateway.
    Create a CNAME in OVH pointing your custom domain to this value.
    Example: andy-api.k8s  CNAME  <this value>
  EOT
  value = (
    local.enable_custom_domain
    ? aws_api_gateway_domain_name.andy_api[0].regional_domain_name
    : ""
  )
}

output "acm_validation_cname" {
  description = <<-EOT
    DNS record required to validate the ACM certificate.
    Create this CNAME in OVH before the certificate can be issued.
    Format: { name, value } — both are CNAME records.
  EOT
  value = (
    local.enable_custom_domain
    ? {
      name  = tolist(aws_acm_certificate.andy_api[0].domain_validation_options)[0].resource_record_name
      value = tolist(aws_acm_certificate.andy_api[0].domain_validation_options)[0].resource_record_value
    }
    : null
  )
}
