yamlApplicationConfig:
  kafka:
    clusters:
      - name: kafka
        bootstrapServers: kafka.kafka.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false