provisioning:
  enabled: true
  topics:
    - name: "toydata-topic-temperature-v1"
      partitions: 2
      replicationFactor: 2
      config:
        retention.ms: 604800000
        segment.bytes: 1073741824
controller:
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Gi
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
