apiVersion: apps/v1
kind: Deployment
metadata:
  name: andy-api
  namespace: toy-data-project
  labels:
    app: andy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andy-api
  template:
    metadata:
      labels:
        app: andy-api
    spec:
      containers:
        - name: andy-api
          image: registry.k8s.our-cluster.ovh/toy-data-project/andy-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: KAFKA_BROKER
              value: kafka.kafka.svc.cluster.local:9092
            - name: KAFKA_TOPIC
              value: toydata-topic-temperature-v1
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
